In [1]:
attach(a)

NameError: name 'attach' is not defined

In [10]:
import pandas as pd
import numpy as np
from scipy.stats import kurtosis
from scipy.stats import skew

In [11]:
df=pd.read_csv("Q9_a.csv")

In [13]:
skew(df)

array([ 0.        , -0.11395477,  0.78248352])

In [14]:
kurtosis(df)

array([-1.20096038, -0.57714742,  0.24801866])

In [15]:
a=pd.read_csv("Q9_b.csv")

In [16]:
skew(a)

array([ 0.        ,  1.58145368, -0.60330993])

In [19]:
kurtosis(a)

array([-1.20036585,  2.72352149,  0.81946588])

In [20]:
from scipy import stats

In [24]:
stats.t.ppf(0.97,df=1999)

1.8818614764780113